import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import * as path from 'path';
import Excel from 'exceljs';


import { useState } from "react";

import { api } from "~/utils/api";


type Filter = {
  cbhMasterID: string | undefined,
  cbhDonorID: string | undefined,
  cbhSampleID: string | undefined,
  price: { 
    min: number | undefined, 
    max: number | undefined,
  },
  matrix: string[],
  quantity: {
    min: number | undefined,
    max: number | undefined,
  },
  unit: string[],
  labParameter: string[],
  resultInterpretation: string[],
  //resultNumerical
  resultUnit: string[],
  diagnosis: string[],
  ICDCode: string[]
}

const Home: NextPage = () => {

  const request = api.dataControler.upload.useMutation()

  const defaultFilter: Filter = {
    cbhMasterID: undefined, 
    cbhDonorID: undefined, 
    cbhSampleID: undefined,
    price: {
      min: undefined,
      max: undefined,
    },
    matrix: [],
    quantity: {
      min: undefined,
      max: undefined,
    },
    unit: [],
    labParameter: [],
    resultInterpretation: [],
    resultUnit: [],
    diagnosis: [],
    ICDCode: []
  }

  const defaultShow: boolean[] = []

  const [page,] = useState<number>(1)
  const [pagelength,] = useState<number>(10)
  const [search,] = useState<string | undefined>()
  const [filter,] = useState<Filter>(defaultFilter)

  const { data: samples, refetch: refetchSamples } = api.samples.getAll.useQuery(
    { pages: page, lines: pagelength, search: search, filter: filter }
  )

  for(let i = 0; i < pagelength; i++){
    defaultShow.push(false)
  }

  const [show, setShow] = useState<boolean[]>(defaultShow)

  const updateState = (index: number) => {
    const newArray = show.map((item, i) => {
      if(index === i){
        return !item
      } else {
        return item
      }
    })
    setShow(newArray)
  }

  return (
    <>
      <Head>
        <title>CBH Harmonizer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        Main
        <button onClick = {() => request.mutate("joa")}> Upload </button>

        <div className="mx-4 my-5">
          <table className="w-full text-lg border-separate border-spacing-y-1 max-h-[50vh] overflow-y-auto">
            <thead>
              <tr className="bg-[rgb(131,182,94)] text-gray-100 font-extralight">
                <th className="py-2 font-extralight border-dotted rounded-l-xl border-black border-r-2">Cart</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">CBHDonorID</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">CBHSampleID</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Details</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Matrix</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Quantity</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Unit</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Age</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Gender</th>
                <th className="py-2 font-extralight rounded-r-xl">Price</th>
              </tr>
            </thead>
            <tbody>
              {samples?.map((sample, index) => (
                <>
                  <tr key={index} className="text-center">
                    <td className="items-center text-2xl bg-gray-300 rounded-l-xl"><button>Add</button></td>
                    <td className="py-2 px-3 bg-gray-300">{sample.CBH_Donor_ID}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.CBH_Sample_ID}</td>
                    <td className="items-center text-2xl bg-gray-300"><button onClick={() => {updateState(index)}}>Show</button></td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Matrix}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Quantity}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Unit}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Age}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Gender}</td>
                    <td className="py-2 px-3 bg-gray-300 rounded-r-xl">{sample.Price} €</td> 
                  </tr>
                  <tr className={`mx-5 ${show[index] ? "" : "hidden"}`}>
                    <td colSpan={2} className="px-5 bg-gray-200">
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">General Data</strong>
                        <span>CBH Master ID:</span> {sample.CBH_Master_ID ?? "NaN"}
                        <span>Storage Temperature:</span> {sample.Storage_Temperature ?? "NaN"}
                        <span>Freeze Thaw Cycles:</span> {sample.Freeze_Thaw_Cycles ?? "NaN"}
                        <span>Infectious Disease Test Result:</span> {(sample.Infectious_Disease_Test_Result !== null && sample.Infectious_Disease_Test_Result !== "") ? sample.Infectious_Disease_Test_Result : "NaN"}
                        <span>Sample Condition:</span> {sample.Sample_Condition ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={2}>
                      <div className="grid grid-cols-2 ">
                        <strong className="col-span-2">Donor</strong>
                        <span>Age:</span> {sample.Age ?? "NaN"}
                        <span>Gender:</span> {sample.Gender ?? "NaN"}
                        <span>Ethnicity:</span> {sample.Ethnicity ?? "NaN"}
                        <strong className="col-span-2 mt-2">Ethics</strong>
                        <span>Procurement Type:</span> {sample.Procurement_Type ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={2}>
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">Laboratory</strong>
                        <span>Lab Parameter</span> {sample.Lab_Parameter ?? "NaN"}
                        <span>Result Raw:</span> {sample.Result_Raw ?? "NaN"}
                        <span>Result Unit:</span> {sample.Result_Unit ?? "NaN"}
                        <span>Interpretation:</span> {sample.Result_Interpretation ?? "NaN"}
                        <span>Cut Off Raw:</span> {sample.Cut_Off_Raw ?? "NaN"}
                        <span>Cut Off Unit:</span> {sample.Result_Unit ?? "NaN"}
                        <span>Test Method:</span> {sample.Test_Method ?? "NaN"}
                        <span>Test System:</span> {sample.Test_System ?? "NaN"}
                        <span>Test System Manuf.:</span> {sample.Test_System_Manufacturer ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={4}>
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">Clinical Diagnosis</strong>
                        <span>Diagnosis:</span> {(sample.Diagnosis !== null && sample.Diagnosis !== "") ? sample.Diagnosis : "NaN"}
                        <span>Diagnosis Remarks:</span> {(sample.Diagnosis_Remarks !== null && sample.Diagnosis_Remarks !== "") ? sample.Diagnosis_Remarks : "NaN"}
                        <strong className="col-span-2 mt-2">Preanalytics</strong>
                        <span>Collection Country:</span> {sample.Country_of_Collection ?? "NaN"}
                        <span>Collection Date:</span> {sample.Date_of_Collection?.toDateString() ?? "NaN"}
                      </div>
                    </td>
                  </tr>
                </>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Home;
